module remote_msgs {
  // ChassisDriverStatus.autodrive_on_off_status
  // const long DEAVTIVE = -1;

  enum ControlMode {
    DEAVTIVE,
    AUTO,
    MANUAL, 
    REMOTE_DIRECT,
    REMOTE_CMD
  };

  // VehicleStatus.vehicle_power_status
  enum PowerModeType {
    POWERMODE_OFF,
    POWERMODE_ACC,
    POWERMODE_ON,
    POWERMODE_CRANK
  };

  struct LanePair {
    long lane_id;
    boolean is_reserve_lane;
    long self_lane_id;
    long left_lane_id;
    long right_lane_id;
  };
  typedef sequence<LanePair> LaneArray;

  struct VehicleStatus {
    // 来自gnss
    double position_longitude;
    double position_latitude;
    double heading;

    // 未知
    float position_altitude;

    // 来自vehicleio
    float speed;
    float yawrate;
    long gear_position;
    float acceleration;
    float steering_angle;
    float wheel_angle;
    long ebrake_status;
    boolean indicator_left;
    boolean indicator_right;
    boolean high_beam_status;
    boolean low_beam_status;
    boolean emergency_light_status;
    unsigned long long timestamp;
    PowerModeType power_mode;

    // 来自ssm
    long loc_lane_id;
    long cruise_lane_id;
    LaneArray local_lanes;

    // 来自control
    boolean driving_efficiency;
    long control_mode;
    //ControlMode control_mode;

    unsigned long vehicle_id;
  };

};