// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FaultReport.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_REMOTE_MSGS_FAULTREPORT_H_
#define _FAST_DDS_GENERATED_REMOTE_MSGS_FAULTREPORT_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(FaultReport_SOURCE)
#define FaultReport_DllAPI __declspec( dllexport )
#else
#define FaultReport_DllAPI __declspec( dllimport )
#endif // FaultReport_SOURCE
#else
#define FaultReport_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define FaultReport_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace remote_msgs {
    typedef std::vector<int32_t> Int32DynamicArray;
    /*!
     * @brief This class represents the structure FaultReport defined by the user in the IDL file.
     * @ingroup FAULTREPORT
     */
    class FaultReport
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport FaultReport();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~FaultReport();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object remote_msgs::FaultReport that will be copied.
         */
        eProsima_user_DllExport FaultReport(
                const FaultReport& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object remote_msgs::FaultReport that will be copied.
         */
        eProsima_user_DllExport FaultReport(
                FaultReport&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object remote_msgs::FaultReport that will be copied.
         */
        eProsima_user_DllExport FaultReport& operator =(
                const FaultReport& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object remote_msgs::FaultReport that will be copied.
         */
        eProsima_user_DllExport FaultReport& operator =(
                FaultReport&& x);

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::FaultReport object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const FaultReport& x) const;

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::FaultReport object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const FaultReport& x) const;

        /*!
         * @brief This function copies the value in member fault_type
         * @param _fault_type New value to be copied in member fault_type
         */
        eProsima_user_DllExport void fault_type(
                const remote_msgs::Int32DynamicArray& _fault_type);

        /*!
         * @brief This function moves the value in member fault_type
         * @param _fault_type New value to be moved in member fault_type
         */
        eProsima_user_DllExport void fault_type(
                remote_msgs::Int32DynamicArray&& _fault_type);

        /*!
         * @brief This function returns a constant reference to member fault_type
         * @return Constant reference to member fault_type
         */
        eProsima_user_DllExport const remote_msgs::Int32DynamicArray& fault_type() const;

        /*!
         * @brief This function returns a reference to member fault_type
         * @return Reference to member fault_type
         */
        eProsima_user_DllExport remote_msgs::Int32DynamicArray& fault_type();

        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const remote_msgs::FaultReport& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        remote_msgs::Int32DynamicArray m_fault_type;
    };
} // namespace remote_msgs

#endif // _FAST_DDS_GENERATED_REMOTE_MSGS_FAULTREPORT_H_