// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DriveState.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "DriveState.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

remote_msgs::StateMachineState::StateMachineState()
{
    // m_driving_state com.eprosima.idl.parser.typecode.PrimitiveTypeCode@28ac3dc3
    m_driving_state = 0;

}

remote_msgs::StateMachineState::~StateMachineState()
{
}

remote_msgs::StateMachineState::StateMachineState(
        const StateMachineState& x)
{
    m_driving_state = x.m_driving_state;
}

remote_msgs::StateMachineState::StateMachineState(
        StateMachineState&& x)
{
    m_driving_state = x.m_driving_state;
}

remote_msgs::StateMachineState& remote_msgs::StateMachineState::operator =(
        const StateMachineState& x)
{

    m_driving_state = x.m_driving_state;

    return *this;
}

remote_msgs::StateMachineState& remote_msgs::StateMachineState::operator =(
        StateMachineState&& x)
{

    m_driving_state = x.m_driving_state;

    return *this;
}

bool remote_msgs::StateMachineState::operator ==(
        const StateMachineState& x) const
{

    return (m_driving_state == x.m_driving_state);
}

bool remote_msgs::StateMachineState::operator !=(
        const StateMachineState& x) const
{
    return !(*this == x);
}

size_t remote_msgs::StateMachineState::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

size_t remote_msgs::StateMachineState::getCdrSerializedSize(
        const remote_msgs::StateMachineState& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    return current_alignment - initial_alignment;
}

void remote_msgs::StateMachineState::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_driving_state;

}

void remote_msgs::StateMachineState::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_driving_state;
}

/*!
 * @brief This function sets a value in member driving_state
 * @param _driving_state New value for member driving_state
 */
void remote_msgs::StateMachineState::driving_state(
        int32_t _driving_state)
{
    m_driving_state = _driving_state;
}

/*!
 * @brief This function returns the value of member driving_state
 * @return Value of member driving_state
 */
int32_t remote_msgs::StateMachineState::driving_state() const
{
    return m_driving_state;
}

/*!
 * @brief This function returns a reference to member driving_state
 * @return Reference to member driving_state
 */
int32_t& remote_msgs::StateMachineState::driving_state()
{
    return m_driving_state;
}


size_t remote_msgs::StateMachineState::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool remote_msgs::StateMachineState::isKeyDefined()
{
    return false;
}

void remote_msgs::StateMachineState::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

