// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DriveState.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_REMOTE_MSGS_DRIVESTATE_H_
#define _FAST_DDS_GENERATED_REMOTE_MSGS_DRIVESTATE_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DriveState_SOURCE)
#define DriveState_DllAPI __declspec( dllexport )
#else
#define DriveState_DllAPI __declspec( dllimport )
#endif // DriveState_SOURCE
#else
#define DriveState_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DriveState_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace remote_msgs {
    /*!
     * @brief This class represents the structure StateMachineState defined by the user in the IDL file.
     * @ingroup DRIVESTATE
     */
    class StateMachineState
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport StateMachineState();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~StateMachineState();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object remote_msgs::StateMachineState that will be copied.
         */
        eProsima_user_DllExport StateMachineState(
                const StateMachineState& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object remote_msgs::StateMachineState that will be copied.
         */
        eProsima_user_DllExport StateMachineState(
                StateMachineState&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object remote_msgs::StateMachineState that will be copied.
         */
        eProsima_user_DllExport StateMachineState& operator =(
                const StateMachineState& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object remote_msgs::StateMachineState that will be copied.
         */
        eProsima_user_DllExport StateMachineState& operator =(
                StateMachineState&& x);

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::StateMachineState object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const StateMachineState& x) const;

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::StateMachineState object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const StateMachineState& x) const;

        /*!
         * @brief This function sets a value in member driving_state
         * @param _driving_state New value for member driving_state
         */
        eProsima_user_DllExport void driving_state(
                int32_t _driving_state);

        /*!
         * @brief This function returns the value of member driving_state
         * @return Value of member driving_state
         */
        eProsima_user_DllExport int32_t driving_state() const;

        /*!
         * @brief This function returns a reference to member driving_state
         * @return Reference to member driving_state
         */
        eProsima_user_DllExport int32_t& driving_state();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const remote_msgs::StateMachineState& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        int32_t m_driving_state;
    };
} // namespace remote_msgs

#endif // _FAST_DDS_GENERATED_REMOTE_MSGS_DRIVESTATE_H_