// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VehicleStatus.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_REMOTE_MSGS_VEHICLESTATUS_H_
#define _FAST_DDS_GENERATED_REMOTE_MSGS_VEHICLESTATUS_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(VehicleStatus_SOURCE)
#define VehicleStatus_DllAPI __declspec( dllexport )
#else
#define VehicleStatus_DllAPI __declspec( dllimport )
#endif // VehicleStatus_SOURCE
#else
#define VehicleStatus_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define VehicleStatus_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace remote_msgs {
    /*!
     * @brief This class represents the enumeration ControlMode defined by the user in the IDL file.
     * @ingroup VEHICLESTATUS
     */
    enum ControlMode : uint32_t
    {
        DEAVTIVE,
        AUTO,
        MANUAL,
        REMOTE_DIRECT,
        REMOTE_CMD
    };
    /*!
     * @brief This class represents the enumeration PowerModeType defined by the user in the IDL file.
     * @ingroup VEHICLESTATUS
     */
    enum PowerModeType : uint32_t
    {
        POWERMODE_OFF,
        POWERMODE_ACC,
        POWERMODE_ON,
        POWERMODE_CRANK
    };
    /*!
     * @brief This class represents the structure LanePair defined by the user in the IDL file.
     * @ingroup VEHICLESTATUS
     */
    class LanePair
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport LanePair();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~LanePair();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object remote_msgs::LanePair that will be copied.
         */
        eProsima_user_DllExport LanePair(
                const LanePair& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object remote_msgs::LanePair that will be copied.
         */
        eProsima_user_DllExport LanePair(
                LanePair&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object remote_msgs::LanePair that will be copied.
         */
        eProsima_user_DllExport LanePair& operator =(
                const LanePair& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object remote_msgs::LanePair that will be copied.
         */
        eProsima_user_DllExport LanePair& operator =(
                LanePair&& x);

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::LanePair object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const LanePair& x) const;

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::LanePair object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const LanePair& x) const;

        /*!
         * @brief This function sets a value in member lane_id
         * @param _lane_id New value for member lane_id
         */
        eProsima_user_DllExport void lane_id(
                int32_t _lane_id);

        /*!
         * @brief This function returns the value of member lane_id
         * @return Value of member lane_id
         */
        eProsima_user_DllExport int32_t lane_id() const;

        /*!
         * @brief This function returns a reference to member lane_id
         * @return Reference to member lane_id
         */
        eProsima_user_DllExport int32_t& lane_id();

        /*!
         * @brief This function sets a value in member is_reserve_lane
         * @param _is_reserve_lane New value for member is_reserve_lane
         */
        eProsima_user_DllExport void is_reserve_lane(
                bool _is_reserve_lane);

        /*!
         * @brief This function returns the value of member is_reserve_lane
         * @return Value of member is_reserve_lane
         */
        eProsima_user_DllExport bool is_reserve_lane() const;

        /*!
         * @brief This function returns a reference to member is_reserve_lane
         * @return Reference to member is_reserve_lane
         */
        eProsima_user_DllExport bool& is_reserve_lane();

        /*!
         * @brief This function sets a value in member self_lane_id
         * @param _self_lane_id New value for member self_lane_id
         */
        eProsima_user_DllExport void self_lane_id(
                int32_t _self_lane_id);

        /*!
         * @brief This function returns the value of member self_lane_id
         * @return Value of member self_lane_id
         */
        eProsima_user_DllExport int32_t self_lane_id() const;

        /*!
         * @brief This function returns a reference to member self_lane_id
         * @return Reference to member self_lane_id
         */
        eProsima_user_DllExport int32_t& self_lane_id();

        /*!
         * @brief This function sets a value in member left_lane_id
         * @param _left_lane_id New value for member left_lane_id
         */
        eProsima_user_DllExport void left_lane_id(
                int32_t _left_lane_id);

        /*!
         * @brief This function returns the value of member left_lane_id
         * @return Value of member left_lane_id
         */
        eProsima_user_DllExport int32_t left_lane_id() const;

        /*!
         * @brief This function returns a reference to member left_lane_id
         * @return Reference to member left_lane_id
         */
        eProsima_user_DllExport int32_t& left_lane_id();

        /*!
         * @brief This function sets a value in member right_lane_id
         * @param _right_lane_id New value for member right_lane_id
         */
        eProsima_user_DllExport void right_lane_id(
                int32_t _right_lane_id);

        /*!
         * @brief This function returns the value of member right_lane_id
         * @return Value of member right_lane_id
         */
        eProsima_user_DllExport int32_t right_lane_id() const;

        /*!
         * @brief This function returns a reference to member right_lane_id
         * @return Reference to member right_lane_id
         */
        eProsima_user_DllExport int32_t& right_lane_id();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const remote_msgs::LanePair& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        int32_t m_lane_id;
        bool m_is_reserve_lane;
        int32_t m_self_lane_id;
        int32_t m_left_lane_id;
        int32_t m_right_lane_id;
    };
    typedef std::vector<remote_msgs::LanePair> LaneArray;
    /*!
     * @brief This class represents the structure VehicleStatus defined by the user in the IDL file.
     * @ingroup VEHICLESTATUS
     */
    class VehicleStatus
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport VehicleStatus();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~VehicleStatus();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object remote_msgs::VehicleStatus that will be copied.
         */
        eProsima_user_DllExport VehicleStatus(
                const VehicleStatus& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object remote_msgs::VehicleStatus that will be copied.
         */
        eProsima_user_DllExport VehicleStatus(
                VehicleStatus&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object remote_msgs::VehicleStatus that will be copied.
         */
        eProsima_user_DllExport VehicleStatus& operator =(
                const VehicleStatus& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object remote_msgs::VehicleStatus that will be copied.
         */
        eProsima_user_DllExport VehicleStatus& operator =(
                VehicleStatus&& x);

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::VehicleStatus object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const VehicleStatus& x) const;

        /*!
         * @brief Comparison operator.
         * @param x remote_msgs::VehicleStatus object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const VehicleStatus& x) const;

        /*!
         * @brief This function sets a value in member position_longitude
         * @param _position_longitude New value for member position_longitude
         */
        eProsima_user_DllExport void position_longitude(
                double _position_longitude);

        /*!
         * @brief This function returns the value of member position_longitude
         * @return Value of member position_longitude
         */
        eProsima_user_DllExport double position_longitude() const;

        /*!
         * @brief This function returns a reference to member position_longitude
         * @return Reference to member position_longitude
         */
        eProsima_user_DllExport double& position_longitude();

        /*!
         * @brief This function sets a value in member position_latitude
         * @param _position_latitude New value for member position_latitude
         */
        eProsima_user_DllExport void position_latitude(
                double _position_latitude);

        /*!
         * @brief This function returns the value of member position_latitude
         * @return Value of member position_latitude
         */
        eProsima_user_DllExport double position_latitude() const;

        /*!
         * @brief This function returns a reference to member position_latitude
         * @return Reference to member position_latitude
         */
        eProsima_user_DllExport double& position_latitude();

        /*!
         * @brief This function sets a value in member heading
         * @param _heading New value for member heading
         */
        eProsima_user_DllExport void heading(
                double _heading);

        /*!
         * @brief This function returns the value of member heading
         * @return Value of member heading
         */
        eProsima_user_DllExport double heading() const;

        /*!
         * @brief This function returns a reference to member heading
         * @return Reference to member heading
         */
        eProsima_user_DllExport double& heading();

        /*!
         * @brief This function sets a value in member position_altitude
         * @param _position_altitude New value for member position_altitude
         */
        eProsima_user_DllExport void position_altitude(
                float _position_altitude);

        /*!
         * @brief This function returns the value of member position_altitude
         * @return Value of member position_altitude
         */
        eProsima_user_DllExport float position_altitude() const;

        /*!
         * @brief This function returns a reference to member position_altitude
         * @return Reference to member position_altitude
         */
        eProsima_user_DllExport float& position_altitude();

        /*!
         * @brief This function sets a value in member speed
         * @param _speed New value for member speed
         */
        eProsima_user_DllExport void speed(
                float _speed);

        /*!
         * @brief This function returns the value of member speed
         * @return Value of member speed
         */
        eProsima_user_DllExport float speed() const;

        /*!
         * @brief This function returns a reference to member speed
         * @return Reference to member speed
         */
        eProsima_user_DllExport float& speed();

        /*!
         * @brief This function sets a value in member yawrate
         * @param _yawrate New value for member yawrate
         */
        eProsima_user_DllExport void yawrate(
                float _yawrate);

        /*!
         * @brief This function returns the value of member yawrate
         * @return Value of member yawrate
         */
        eProsima_user_DllExport float yawrate() const;

        /*!
         * @brief This function returns a reference to member yawrate
         * @return Reference to member yawrate
         */
        eProsima_user_DllExport float& yawrate();

        /*!
         * @brief This function sets a value in member gear_position
         * @param _gear_position New value for member gear_position
         */
        eProsima_user_DllExport void gear_position(
                int32_t _gear_position);

        /*!
         * @brief This function returns the value of member gear_position
         * @return Value of member gear_position
         */
        eProsima_user_DllExport int32_t gear_position() const;

        /*!
         * @brief This function returns a reference to member gear_position
         * @return Reference to member gear_position
         */
        eProsima_user_DllExport int32_t& gear_position();

        /*!
         * @brief This function sets a value in member acceleration
         * @param _acceleration New value for member acceleration
         */
        eProsima_user_DllExport void acceleration(
                float _acceleration);

        /*!
         * @brief This function returns the value of member acceleration
         * @return Value of member acceleration
         */
        eProsima_user_DllExport float acceleration() const;

        /*!
         * @brief This function returns a reference to member acceleration
         * @return Reference to member acceleration
         */
        eProsima_user_DllExport float& acceleration();

        /*!
         * @brief This function sets a value in member steering_angle
         * @param _steering_angle New value for member steering_angle
         */
        eProsima_user_DllExport void steering_angle(
                float _steering_angle);

        /*!
         * @brief This function returns the value of member steering_angle
         * @return Value of member steering_angle
         */
        eProsima_user_DllExport float steering_angle() const;

        /*!
         * @brief This function returns a reference to member steering_angle
         * @return Reference to member steering_angle
         */
        eProsima_user_DllExport float& steering_angle();

        /*!
         * @brief This function sets a value in member wheel_angle
         * @param _wheel_angle New value for member wheel_angle
         */
        eProsima_user_DllExport void wheel_angle(
                float _wheel_angle);

        /*!
         * @brief This function returns the value of member wheel_angle
         * @return Value of member wheel_angle
         */
        eProsima_user_DllExport float wheel_angle() const;

        /*!
         * @brief This function returns a reference to member wheel_angle
         * @return Reference to member wheel_angle
         */
        eProsima_user_DllExport float& wheel_angle();

        /*!
         * @brief This function sets a value in member ebrake_status
         * @param _ebrake_status New value for member ebrake_status
         */
        eProsima_user_DllExport void ebrake_status(
                int32_t _ebrake_status);

        /*!
         * @brief This function returns the value of member ebrake_status
         * @return Value of member ebrake_status
         */
        eProsima_user_DllExport int32_t ebrake_status() const;

        /*!
         * @brief This function returns a reference to member ebrake_status
         * @return Reference to member ebrake_status
         */
        eProsima_user_DllExport int32_t& ebrake_status();

        /*!
         * @brief This function sets a value in member indicator_left
         * @param _indicator_left New value for member indicator_left
         */
        eProsima_user_DllExport void indicator_left(
                bool _indicator_left);

        /*!
         * @brief This function returns the value of member indicator_left
         * @return Value of member indicator_left
         */
        eProsima_user_DllExport bool indicator_left() const;

        /*!
         * @brief This function returns a reference to member indicator_left
         * @return Reference to member indicator_left
         */
        eProsima_user_DllExport bool& indicator_left();

        /*!
         * @brief This function sets a value in member indicator_right
         * @param _indicator_right New value for member indicator_right
         */
        eProsima_user_DllExport void indicator_right(
                bool _indicator_right);

        /*!
         * @brief This function returns the value of member indicator_right
         * @return Value of member indicator_right
         */
        eProsima_user_DllExport bool indicator_right() const;

        /*!
         * @brief This function returns a reference to member indicator_right
         * @return Reference to member indicator_right
         */
        eProsima_user_DllExport bool& indicator_right();

        /*!
         * @brief This function sets a value in member high_beam_status
         * @param _high_beam_status New value for member high_beam_status
         */
        eProsima_user_DllExport void high_beam_status(
                bool _high_beam_status);

        /*!
         * @brief This function returns the value of member high_beam_status
         * @return Value of member high_beam_status
         */
        eProsima_user_DllExport bool high_beam_status() const;

        /*!
         * @brief This function returns a reference to member high_beam_status
         * @return Reference to member high_beam_status
         */
        eProsima_user_DllExport bool& high_beam_status();

        /*!
         * @brief This function sets a value in member low_beam_status
         * @param _low_beam_status New value for member low_beam_status
         */
        eProsima_user_DllExport void low_beam_status(
                bool _low_beam_status);

        /*!
         * @brief This function returns the value of member low_beam_status
         * @return Value of member low_beam_status
         */
        eProsima_user_DllExport bool low_beam_status() const;

        /*!
         * @brief This function returns a reference to member low_beam_status
         * @return Reference to member low_beam_status
         */
        eProsima_user_DllExport bool& low_beam_status();

        /*!
         * @brief This function sets a value in member emergency_light_status
         * @param _emergency_light_status New value for member emergency_light_status
         */
        eProsima_user_DllExport void emergency_light_status(
                bool _emergency_light_status);

        /*!
         * @brief This function returns the value of member emergency_light_status
         * @return Value of member emergency_light_status
         */
        eProsima_user_DllExport bool emergency_light_status() const;

        /*!
         * @brief This function returns a reference to member emergency_light_status
         * @return Reference to member emergency_light_status
         */
        eProsima_user_DllExport bool& emergency_light_status();

        /*!
         * @brief This function sets a value in member timestamp
         * @param _timestamp New value for member timestamp
         */
        eProsima_user_DllExport void timestamp(
                uint64_t _timestamp);

        /*!
         * @brief This function returns the value of member timestamp
         * @return Value of member timestamp
         */
        eProsima_user_DllExport uint64_t timestamp() const;

        /*!
         * @brief This function returns a reference to member timestamp
         * @return Reference to member timestamp
         */
        eProsima_user_DllExport uint64_t& timestamp();

        /*!
         * @brief This function sets a value in member power_mode
         * @param _power_mode New value for member power_mode
         */
        eProsima_user_DllExport void power_mode(
                remote_msgs::PowerModeType _power_mode);

        /*!
         * @brief This function returns the value of member power_mode
         * @return Value of member power_mode
         */
        eProsima_user_DllExport remote_msgs::PowerModeType power_mode() const;

        /*!
         * @brief This function returns a reference to member power_mode
         * @return Reference to member power_mode
         */
        eProsima_user_DllExport remote_msgs::PowerModeType& power_mode();

        /*!
         * @brief This function sets a value in member loc_lane_id
         * @param _loc_lane_id New value for member loc_lane_id
         */
        eProsima_user_DllExport void loc_lane_id(
                int32_t _loc_lane_id);

        /*!
         * @brief This function returns the value of member loc_lane_id
         * @return Value of member loc_lane_id
         */
        eProsima_user_DllExport int32_t loc_lane_id() const;

        /*!
         * @brief This function returns a reference to member loc_lane_id
         * @return Reference to member loc_lane_id
         */
        eProsima_user_DllExport int32_t& loc_lane_id();

        /*!
         * @brief This function sets a value in member cruise_lane_id
         * @param _cruise_lane_id New value for member cruise_lane_id
         */
        eProsima_user_DllExport void cruise_lane_id(
                int32_t _cruise_lane_id);

        /*!
         * @brief This function returns the value of member cruise_lane_id
         * @return Value of member cruise_lane_id
         */
        eProsima_user_DllExport int32_t cruise_lane_id() const;

        /*!
         * @brief This function returns a reference to member cruise_lane_id
         * @return Reference to member cruise_lane_id
         */
        eProsima_user_DllExport int32_t& cruise_lane_id();

        /*!
         * @brief This function copies the value in member local_lanes
         * @param _local_lanes New value to be copied in member local_lanes
         */
        eProsima_user_DllExport void local_lanes(
                const remote_msgs::LaneArray& _local_lanes);

        /*!
         * @brief This function moves the value in member local_lanes
         * @param _local_lanes New value to be moved in member local_lanes
         */
        eProsima_user_DllExport void local_lanes(
                remote_msgs::LaneArray&& _local_lanes);

        /*!
         * @brief This function returns a constant reference to member local_lanes
         * @return Constant reference to member local_lanes
         */
        eProsima_user_DllExport const remote_msgs::LaneArray& local_lanes() const;

        /*!
         * @brief This function returns a reference to member local_lanes
         * @return Reference to member local_lanes
         */
        eProsima_user_DllExport remote_msgs::LaneArray& local_lanes();
        /*!
         * @brief This function sets a value in member driving_efficiency
         * @param _driving_efficiency New value for member driving_efficiency
         */
        eProsima_user_DllExport void driving_efficiency(
                bool _driving_efficiency);

        /*!
         * @brief This function returns the value of member driving_efficiency
         * @return Value of member driving_efficiency
         */
        eProsima_user_DllExport bool driving_efficiency() const;

        /*!
         * @brief This function returns a reference to member driving_efficiency
         * @return Reference to member driving_efficiency
         */
        eProsima_user_DllExport bool& driving_efficiency();

        /*!
         * @brief This function sets a value in member control_mode
         * @param _control_mode New value for member control_mode
         */
        eProsima_user_DllExport void control_mode(
                int32_t _control_mode);

        /*!
         * @brief This function returns the value of member control_mode
         * @return Value of member control_mode
         */
        eProsima_user_DllExport int32_t control_mode() const;

        /*!
         * @brief This function returns a reference to member control_mode
         * @return Reference to member control_mode
         */
        eProsima_user_DllExport int32_t& control_mode();

        /*!
         * @brief This function sets a value in member vehicle_id
         * @param _vehicle_id New value for member vehicle_id
         */
        eProsima_user_DllExport void vehicle_id(
                uint32_t _vehicle_id);

        /*!
         * @brief This function returns the value of member vehicle_id
         * @return Value of member vehicle_id
         */
        eProsima_user_DllExport uint32_t vehicle_id() const;

        /*!
         * @brief This function returns a reference to member vehicle_id
         * @return Reference to member vehicle_id
         */
        eProsima_user_DllExport uint32_t& vehicle_id();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const remote_msgs::VehicleStatus& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        double m_position_longitude;
        double m_position_latitude;
        double m_heading;
        float m_position_altitude;
        float m_speed;
        float m_yawrate;
        int32_t m_gear_position;
        float m_acceleration;
        float m_steering_angle;
        float m_wheel_angle;
        int32_t m_ebrake_status;
        bool m_indicator_left;
        bool m_indicator_right;
        bool m_high_beam_status;
        bool m_low_beam_status;
        bool m_emergency_light_status;
        uint64_t m_timestamp;
        remote_msgs::PowerModeType m_power_mode;
        int32_t m_loc_lane_id;
        int32_t m_cruise_lane_id;
        remote_msgs::LaneArray m_local_lanes;
        bool m_driving_efficiency;
        int32_t m_control_mode;
        uint32_t m_vehicle_id;
    };
} // namespace remote_msgs

#endif // _FAST_DDS_GENERATED_REMOTE_MSGS_VEHICLESTATUS_H_