// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file FaultReport.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "FaultReport.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>


remote_msgs::FaultReport::FaultReport()
{
    // m_fault_type com.eprosima.idl.parser.typecode.AliasTypeCode@25359ed8


}

remote_msgs::FaultReport::~FaultReport()
{
}

remote_msgs::FaultReport::FaultReport(
        const FaultReport& x)
{
    m_fault_type = x.m_fault_type;
}

remote_msgs::FaultReport::FaultReport(
        FaultReport&& x)
{
    m_fault_type = std::move(x.m_fault_type);
}

remote_msgs::FaultReport& remote_msgs::FaultReport::operator =(
        const FaultReport& x)
{

    m_fault_type = x.m_fault_type;

    return *this;
}

remote_msgs::FaultReport& remote_msgs::FaultReport::operator =(
        FaultReport&& x)
{

    m_fault_type = std::move(x.m_fault_type);

    return *this;
}

bool remote_msgs::FaultReport::operator ==(
        const FaultReport& x) const
{

    return (m_fault_type == x.m_fault_type);
}

bool remote_msgs::FaultReport::operator !=(
        const FaultReport& x) const
{
    return !(*this == x);
}

size_t remote_msgs::FaultReport::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t remote_msgs::FaultReport::getCdrSerializedSize(
        const remote_msgs::FaultReport& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.fault_type().size() > 0)
    {
        current_alignment += (data.fault_type().size() * 4) + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);
    }



    return current_alignment - initial_alignment;
}

void remote_msgs::FaultReport::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_fault_type;
}

void remote_msgs::FaultReport::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_fault_type;}

/*!
 * @brief This function copies the value in member fault_type
 * @param _fault_type New value to be copied in member fault_type
 */
void remote_msgs::FaultReport::fault_type(
        const remote_msgs::Int32DynamicArray& _fault_type)
{
    m_fault_type = _fault_type;
}

/*!
 * @brief This function moves the value in member fault_type
 * @param _fault_type New value to be moved in member fault_type
 */
void remote_msgs::FaultReport::fault_type(
        remote_msgs::Int32DynamicArray&& _fault_type)
{
    m_fault_type = std::move(_fault_type);
}

/*!
 * @brief This function returns a constant reference to member fault_type
 * @return Constant reference to member fault_type
 */
const remote_msgs::Int32DynamicArray& remote_msgs::FaultReport::fault_type() const
{
    return m_fault_type;
}

/*!
 * @brief This function returns a reference to member fault_type
 * @return Reference to member fault_type
 */
remote_msgs::Int32DynamicArray& remote_msgs::FaultReport::fault_type()
{
    return m_fault_type;
}

size_t remote_msgs::FaultReport::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool remote_msgs::FaultReport::isKeyDefined()
{
    return false;
}

void remote_msgs::FaultReport::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}

