// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TSPCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TSPCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

zhijiayun::TSPCommand::TSPCommand()
{
    // m_action com.eprosima.idl.parser.typecode.StringTypeCode@c267ef4
    m_action ="";
    // m_module_name com.eprosima.idl.parser.typecode.StringTypeCode@30ee2816
    m_module_name ="";
    // m_command_id com.eprosima.idl.parser.typecode.StringTypeCode@31d7b7bf
    m_command_id ="";
    // m_cloud_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@635eaaf1
    m_cloud_timestamp = 0;
    // m_mqtt_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5c30a9b0
    m_mqtt_timestamp = 0;

}

zhijiayun::TSPCommand::~TSPCommand()
{





}

zhijiayun::TSPCommand::TSPCommand(
        const TSPCommand& x)
{
    m_action = x.m_action;
    m_module_name = x.m_module_name;
    m_command_id = x.m_command_id;
    m_cloud_timestamp = x.m_cloud_timestamp;
    m_mqtt_timestamp = x.m_mqtt_timestamp;
}

zhijiayun::TSPCommand::TSPCommand(
        TSPCommand&& x)
{
    m_action = std::move(x.m_action);
    m_module_name = std::move(x.m_module_name);
    m_command_id = std::move(x.m_command_id);
    m_cloud_timestamp = x.m_cloud_timestamp;
    m_mqtt_timestamp = x.m_mqtt_timestamp;
}

zhijiayun::TSPCommand& zhijiayun::TSPCommand::operator =(
        const TSPCommand& x)
{

    m_action = x.m_action;
    m_module_name = x.m_module_name;
    m_command_id = x.m_command_id;
    m_cloud_timestamp = x.m_cloud_timestamp;
    m_mqtt_timestamp = x.m_mqtt_timestamp;

    return *this;
}

zhijiayun::TSPCommand& zhijiayun::TSPCommand::operator =(
        TSPCommand&& x)
{

    m_action = std::move(x.m_action);
    m_module_name = std::move(x.m_module_name);
    m_command_id = std::move(x.m_command_id);
    m_cloud_timestamp = x.m_cloud_timestamp;
    m_mqtt_timestamp = x.m_mqtt_timestamp;

    return *this;
}

bool zhijiayun::TSPCommand::operator ==(
        const TSPCommand& x) const
{

    return (m_action == x.m_action && m_module_name == x.m_module_name && m_command_id == x.m_command_id && m_cloud_timestamp == x.m_cloud_timestamp && m_mqtt_timestamp == x.m_mqtt_timestamp);
}

bool zhijiayun::TSPCommand::operator !=(
        const TSPCommand& x) const
{
    return !(*this == x);
}

size_t zhijiayun::TSPCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t zhijiayun::TSPCommand::getCdrSerializedSize(
        const zhijiayun::TSPCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.action().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.module_name().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.command_id().size() + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void zhijiayun::TSPCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_action.c_str();
    scdr << m_module_name.c_str();
    scdr << m_command_id.c_str();
    scdr << m_cloud_timestamp;
    scdr << m_mqtt_timestamp;

}

void zhijiayun::TSPCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_action;
    dcdr >> m_module_name;
    dcdr >> m_command_id;
    dcdr >> m_cloud_timestamp;
    dcdr >> m_mqtt_timestamp;
}

/*!
 * @brief This function copies the value in member action
 * @param _action New value to be copied in member action
 */
void zhijiayun::TSPCommand::action(
        const std::string& _action)
{
    m_action = _action;
}

/*!
 * @brief This function moves the value in member action
 * @param _action New value to be moved in member action
 */
void zhijiayun::TSPCommand::action(
        std::string&& _action)
{
    m_action = std::move(_action);
}

/*!
 * @brief This function returns a constant reference to member action
 * @return Constant reference to member action
 */
const std::string& zhijiayun::TSPCommand::action() const
{
    return m_action;
}

/*!
 * @brief This function returns a reference to member action
 * @return Reference to member action
 */
std::string& zhijiayun::TSPCommand::action()
{
    return m_action;
}
/*!
 * @brief This function copies the value in member module_name
 * @param _module_name New value to be copied in member module_name
 */
void zhijiayun::TSPCommand::module_name(
        const std::string& _module_name)
{
    m_module_name = _module_name;
}

/*!
 * @brief This function moves the value in member module_name
 * @param _module_name New value to be moved in member module_name
 */
void zhijiayun::TSPCommand::module_name(
        std::string&& _module_name)
{
    m_module_name = std::move(_module_name);
}

/*!
 * @brief This function returns a constant reference to member module_name
 * @return Constant reference to member module_name
 */
const std::string& zhijiayun::TSPCommand::module_name() const
{
    return m_module_name;
}

/*!
 * @brief This function returns a reference to member module_name
 * @return Reference to member module_name
 */
std::string& zhijiayun::TSPCommand::module_name()
{
    return m_module_name;
}
/*!
 * @brief This function copies the value in member command_id
 * @param _command_id New value to be copied in member command_id
 */
void zhijiayun::TSPCommand::command_id(
        const std::string& _command_id)
{
    m_command_id = _command_id;
}

/*!
 * @brief This function moves the value in member command_id
 * @param _command_id New value to be moved in member command_id
 */
void zhijiayun::TSPCommand::command_id(
        std::string&& _command_id)
{
    m_command_id = std::move(_command_id);
}

/*!
 * @brief This function returns a constant reference to member command_id
 * @return Constant reference to member command_id
 */
const std::string& zhijiayun::TSPCommand::command_id() const
{
    return m_command_id;
}

/*!
 * @brief This function returns a reference to member command_id
 * @return Reference to member command_id
 */
std::string& zhijiayun::TSPCommand::command_id()
{
    return m_command_id;
}
/*!
 * @brief This function sets a value in member cloud_timestamp
 * @param _cloud_timestamp New value for member cloud_timestamp
 */
void zhijiayun::TSPCommand::cloud_timestamp(
        uint64_t _cloud_timestamp)
{
    m_cloud_timestamp = _cloud_timestamp;
}

/*!
 * @brief This function returns the value of member cloud_timestamp
 * @return Value of member cloud_timestamp
 */
uint64_t zhijiayun::TSPCommand::cloud_timestamp() const
{
    return m_cloud_timestamp;
}

/*!
 * @brief This function returns a reference to member cloud_timestamp
 * @return Reference to member cloud_timestamp
 */
uint64_t& zhijiayun::TSPCommand::cloud_timestamp()
{
    return m_cloud_timestamp;
}

/*!
 * @brief This function sets a value in member mqtt_timestamp
 * @param _mqtt_timestamp New value for member mqtt_timestamp
 */
void zhijiayun::TSPCommand::mqtt_timestamp(
        uint64_t _mqtt_timestamp)
{
    m_mqtt_timestamp = _mqtt_timestamp;
}

/*!
 * @brief This function returns the value of member mqtt_timestamp
 * @return Value of member mqtt_timestamp
 */
uint64_t zhijiayun::TSPCommand::mqtt_timestamp() const
{
    return m_mqtt_timestamp;
}

/*!
 * @brief This function returns a reference to member mqtt_timestamp
 * @return Reference to member mqtt_timestamp
 */
uint64_t& zhijiayun::TSPCommand::mqtt_timestamp()
{
    return m_mqtt_timestamp;
}


size_t zhijiayun::TSPCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;








    return current_align;
}

bool zhijiayun::TSPCommand::isKeyDefined()
{
    return false;
}

void zhijiayun::TSPCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}

