// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TSPCommand.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "TSPCommand.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

remote_msgs::TSPCommand::TSPCommand()
{
    // m_action com.eprosima.idl.parser.typecode.StringTypeCode@32eebfca
    m_action ="";
    // m_module_name com.eprosima.idl.parser.typecode.StringTypeCode@4e718207
    m_module_name ="";
    // m_requestId com.eprosima.idl.parser.typecode.StringTypeCode@1d371b2d
    m_requestId ="";
    // m_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@543c6f6d
    m_timestamp = 0;
    // m_mqttsend_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@13eb8acf
    m_mqttsend_timestamp = 0;

}

remote_msgs::TSPCommand::~TSPCommand()
{





}

remote_msgs::TSPCommand::TSPCommand(
        const TSPCommand& x)
{
    m_action = x.m_action;
    m_module_name = x.m_module_name;
    m_requestId = x.m_requestId;
    m_timestamp = x.m_timestamp;
    m_mqttsend_timestamp = x.m_mqttsend_timestamp;
}

remote_msgs::TSPCommand::TSPCommand(
        TSPCommand&& x)
{
    m_action = std::move(x.m_action);
    m_module_name = std::move(x.m_module_name);
    m_requestId = std::move(x.m_requestId);
    m_timestamp = x.m_timestamp;
    m_mqttsend_timestamp = x.m_mqttsend_timestamp;
}

remote_msgs::TSPCommand& remote_msgs::TSPCommand::operator =(
        const TSPCommand& x)
{

    m_action = x.m_action;
    m_module_name = x.m_module_name;
    m_requestId = x.m_requestId;
    m_timestamp = x.m_timestamp;
    m_mqttsend_timestamp = x.m_mqttsend_timestamp;

    return *this;
}

remote_msgs::TSPCommand& remote_msgs::TSPCommand::operator =(
        TSPCommand&& x)
{

    m_action = std::move(x.m_action);
    m_module_name = std::move(x.m_module_name);
    m_requestId = std::move(x.m_requestId);
    m_timestamp = x.m_timestamp;
    m_mqttsend_timestamp = x.m_mqttsend_timestamp;

    return *this;
}

bool remote_msgs::TSPCommand::operator ==(
        const TSPCommand& x) const
{

    return (m_action == x.m_action && m_module_name == x.m_module_name && m_requestId == x.m_requestId && m_timestamp == x.m_timestamp && m_mqttsend_timestamp == x.m_mqttsend_timestamp);
}

bool remote_msgs::TSPCommand::operator !=(
        const TSPCommand& x) const
{
    return !(*this == x);
}

size_t remote_msgs::TSPCommand::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

size_t remote_msgs::TSPCommand::getCdrSerializedSize(
        const remote_msgs::TSPCommand& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.action().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.module_name().size() + 1;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + data.requestId().size() + 1;

    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);



    return current_alignment - initial_alignment;
}

void remote_msgs::TSPCommand::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_action.c_str();
    scdr << m_module_name.c_str();
    scdr << m_requestId.c_str();
    scdr << m_timestamp;
    scdr << m_mqttsend_timestamp;

}

void remote_msgs::TSPCommand::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_action;
    dcdr >> m_module_name;
    dcdr >> m_requestId;
    dcdr >> m_timestamp;
    dcdr >> m_mqttsend_timestamp;
}

/*!
 * @brief This function copies the value in member action
 * @param _action New value to be copied in member action
 */
void remote_msgs::TSPCommand::action(
        const std::string& _action)
{
    m_action = _action;
}

/*!
 * @brief This function moves the value in member action
 * @param _action New value to be moved in member action
 */
void remote_msgs::TSPCommand::action(
        std::string&& _action)
{
    m_action = std::move(_action);
}

/*!
 * @brief This function returns a constant reference to member action
 * @return Constant reference to member action
 */
const std::string& remote_msgs::TSPCommand::action() const
{
    return m_action;
}

/*!
 * @brief This function returns a reference to member action
 * @return Reference to member action
 */
std::string& remote_msgs::TSPCommand::action()
{
    return m_action;
}
/*!
 * @brief This function copies the value in member module_name
 * @param _module_name New value to be copied in member module_name
 */
void remote_msgs::TSPCommand::module_name(
        const std::string& _module_name)
{
    m_module_name = _module_name;
}

/*!
 * @brief This function moves the value in member module_name
 * @param _module_name New value to be moved in member module_name
 */
void remote_msgs::TSPCommand::module_name(
        std::string&& _module_name)
{
    m_module_name = std::move(_module_name);
}

/*!
 * @brief This function returns a constant reference to member module_name
 * @return Constant reference to member module_name
 */
const std::string& remote_msgs::TSPCommand::module_name() const
{
    return m_module_name;
}

/*!
 * @brief This function returns a reference to member module_name
 * @return Reference to member module_name
 */
std::string& remote_msgs::TSPCommand::module_name()
{
    return m_module_name;
}
/*!
 * @brief This function copies the value in member requestId
 * @param _requestId New value to be copied in member requestId
 */
void remote_msgs::TSPCommand::requestId(
        const std::string& _requestId)
{
    m_requestId = _requestId;
}

/*!
 * @brief This function moves the value in member requestId
 * @param _requestId New value to be moved in member requestId
 */
void remote_msgs::TSPCommand::requestId(
        std::string&& _requestId)
{
    m_requestId = std::move(_requestId);
}

/*!
 * @brief This function returns a constant reference to member requestId
 * @return Constant reference to member requestId
 */
const std::string& remote_msgs::TSPCommand::requestId() const
{
    return m_requestId;
}

/*!
 * @brief This function returns a reference to member requestId
 * @return Reference to member requestId
 */
std::string& remote_msgs::TSPCommand::requestId()
{
    return m_requestId;
}
/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void remote_msgs::TSPCommand::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t remote_msgs::TSPCommand::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& remote_msgs::TSPCommand::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function sets a value in member mqttsend_timestamp
 * @param _mqttsend_timestamp New value for member mqttsend_timestamp
 */
void remote_msgs::TSPCommand::mqttsend_timestamp(
        uint64_t _mqttsend_timestamp)
{
    m_mqttsend_timestamp = _mqttsend_timestamp;
}

/*!
 * @brief This function returns the value of member mqttsend_timestamp
 * @return Value of member mqttsend_timestamp
 */
uint64_t remote_msgs::TSPCommand::mqttsend_timestamp() const
{
    return m_mqttsend_timestamp;
}

/*!
 * @brief This function returns a reference to member mqttsend_timestamp
 * @return Reference to member mqttsend_timestamp
 */
uint64_t& remote_msgs::TSPCommand::mqttsend_timestamp()
{
    return m_mqttsend_timestamp;
}


size_t remote_msgs::TSPCommand::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;








    return current_align;
}

bool remote_msgs::TSPCommand::isKeyDefined()
{
    return false;
}

void remote_msgs::TSPCommand::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}

