// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file TSPCommand.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ZHIJIAYUN_TSPCOMMAND_H_
#define _FAST_DDS_GENERATED_ZHIJIAYUN_TSPCOMMAND_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(TSPCommand_SOURCE)
#define TSPCommand_DllAPI __declspec( dllexport )
#else
#define TSPCommand_DllAPI __declspec( dllimport )
#endif // TSPCommand_SOURCE
#else
#define TSPCommand_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define TSPCommand_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace zhijiayun {
    /*!
     * @brief This class represents the structure TSPCommand defined by the user in the IDL file.
     * @ingroup TSPCOMMAND
     */
    class TSPCommand
    {
    public:

        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport TSPCommand();

        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~TSPCommand();

        /*!
         * @brief Copy constructor.
         * @param x Reference to the object zhijiayun::TSPCommand that will be copied.
         */
        eProsima_user_DllExport TSPCommand(
                const TSPCommand& x);

        /*!
         * @brief Move constructor.
         * @param x Reference to the object zhijiayun::TSPCommand that will be copied.
         */
        eProsima_user_DllExport TSPCommand(
                TSPCommand&& x);

        /*!
         * @brief Copy assignment.
         * @param x Reference to the object zhijiayun::TSPCommand that will be copied.
         */
        eProsima_user_DllExport TSPCommand& operator =(
                const TSPCommand& x);

        /*!
         * @brief Move assignment.
         * @param x Reference to the object zhijiayun::TSPCommand that will be copied.
         */
        eProsima_user_DllExport TSPCommand& operator =(
                TSPCommand&& x);

        /*!
         * @brief Comparison operator.
         * @param x zhijiayun::TSPCommand object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const TSPCommand& x) const;

        /*!
         * @brief Comparison operator.
         * @param x zhijiayun::TSPCommand object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const TSPCommand& x) const;

        /*!
         * @brief This function copies the value in member action
         * @param _action New value to be copied in member action
         */
        eProsima_user_DllExport void action(
                const std::string& _action);

        /*!
         * @brief This function moves the value in member action
         * @param _action New value to be moved in member action
         */
        eProsima_user_DllExport void action(
                std::string&& _action);

        /*!
         * @brief This function returns a constant reference to member action
         * @return Constant reference to member action
         */
        eProsima_user_DllExport const std::string& action() const;

        /*!
         * @brief This function returns a reference to member action
         * @return Reference to member action
         */
        eProsima_user_DllExport std::string& action();
        /*!
         * @brief This function copies the value in member module_name
         * @param _module_name New value to be copied in member module_name
         */
        eProsima_user_DllExport void module_name(
                const std::string& _module_name);

        /*!
         * @brief This function moves the value in member module_name
         * @param _module_name New value to be moved in member module_name
         */
        eProsima_user_DllExport void module_name(
                std::string&& _module_name);

        /*!
         * @brief This function returns a constant reference to member module_name
         * @return Constant reference to member module_name
         */
        eProsima_user_DllExport const std::string& module_name() const;

        /*!
         * @brief This function returns a reference to member module_name
         * @return Reference to member module_name
         */
        eProsima_user_DllExport std::string& module_name();
        /*!
         * @brief This function copies the value in member command_id
         * @param _command_id New value to be copied in member command_id
         */
        eProsima_user_DllExport void command_id(
                const std::string& _command_id);

        /*!
         * @brief This function moves the value in member command_id
         * @param _command_id New value to be moved in member command_id
         */
        eProsima_user_DllExport void command_id(
                std::string&& _command_id);

        /*!
         * @brief This function returns a constant reference to member command_id
         * @return Constant reference to member command_id
         */
        eProsima_user_DllExport const std::string& command_id() const;

        /*!
         * @brief This function returns a reference to member command_id
         * @return Reference to member command_id
         */
        eProsima_user_DllExport std::string& command_id();
        /*!
         * @brief This function sets a value in member cloud_timestamp
         * @param _cloud_timestamp New value for member cloud_timestamp
         */
        eProsima_user_DllExport void cloud_timestamp(
                uint64_t _cloud_timestamp);

        /*!
         * @brief This function returns the value of member cloud_timestamp
         * @return Value of member cloud_timestamp
         */
        eProsima_user_DllExport uint64_t cloud_timestamp() const;

        /*!
         * @brief This function returns a reference to member cloud_timestamp
         * @return Reference to member cloud_timestamp
         */
        eProsima_user_DllExport uint64_t& cloud_timestamp();

        /*!
         * @brief This function sets a value in member mqtt_timestamp
         * @param _mqtt_timestamp New value for member mqtt_timestamp
         */
        eProsima_user_DllExport void mqtt_timestamp(
                uint64_t _mqtt_timestamp);

        /*!
         * @brief This function returns the value of member mqtt_timestamp
         * @return Value of member mqtt_timestamp
         */
        eProsima_user_DllExport uint64_t mqtt_timestamp() const;

        /*!
         * @brief This function returns a reference to member mqtt_timestamp
         * @return Reference to member mqtt_timestamp
         */
        eProsima_user_DllExport uint64_t& mqtt_timestamp();


        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const zhijiayun::TSPCommand& data,
                size_t current_alignment = 0);


        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;

        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);



        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);

        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();

        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;

    private:

        std::string m_action;
        std::string m_module_name;
        std::string m_command_id;
        uint64_t m_cloud_timestamp;
        uint64_t m_mqtt_timestamp;
    };
} // namespace zhijiayun

#endif // _FAST_DDS_GENERATED_ZHIJIAYUN_TSPCOMMAND_H_