// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VehicleStatus.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VehicleStatus.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>



remote_msgs::LanePair::LanePair()
{
    // m_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1fc2b765
    m_lane_id = 0;
    // m_is_reserve_lane com.eprosima.idl.parser.typecode.PrimitiveTypeCode@75881071
    m_is_reserve_lane = false;
    // m_self_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@2a70a3d8
    m_self_lane_id = 0;
    // m_left_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@289d1c02
    m_left_lane_id = 0;
    // m_right_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@22eeefeb
    m_right_lane_id = 0;

}

remote_msgs::LanePair::~LanePair()
{





}

remote_msgs::LanePair::LanePair(
        const LanePair& x)
{
    m_lane_id = x.m_lane_id;
    m_is_reserve_lane = x.m_is_reserve_lane;
    m_self_lane_id = x.m_self_lane_id;
    m_left_lane_id = x.m_left_lane_id;
    m_right_lane_id = x.m_right_lane_id;
}

remote_msgs::LanePair::LanePair(
        LanePair&& x)
{
    m_lane_id = x.m_lane_id;
    m_is_reserve_lane = x.m_is_reserve_lane;
    m_self_lane_id = x.m_self_lane_id;
    m_left_lane_id = x.m_left_lane_id;
    m_right_lane_id = x.m_right_lane_id;
}

remote_msgs::LanePair& remote_msgs::LanePair::operator =(
        const LanePair& x)
{

    m_lane_id = x.m_lane_id;
    m_is_reserve_lane = x.m_is_reserve_lane;
    m_self_lane_id = x.m_self_lane_id;
    m_left_lane_id = x.m_left_lane_id;
    m_right_lane_id = x.m_right_lane_id;

    return *this;
}

remote_msgs::LanePair& remote_msgs::LanePair::operator =(
        LanePair&& x)
{

    m_lane_id = x.m_lane_id;
    m_is_reserve_lane = x.m_is_reserve_lane;
    m_self_lane_id = x.m_self_lane_id;
    m_left_lane_id = x.m_left_lane_id;
    m_right_lane_id = x.m_right_lane_id;

    return *this;
}

bool remote_msgs::LanePair::operator ==(
        const LanePair& x) const
{

    return (m_lane_id == x.m_lane_id && m_is_reserve_lane == x.m_is_reserve_lane && m_self_lane_id == x.m_self_lane_id && m_left_lane_id == x.m_left_lane_id && m_right_lane_id == x.m_right_lane_id);
}

bool remote_msgs::LanePair::operator !=(
        const LanePair& x) const
{
    return !(*this == x);
}

size_t remote_msgs::LanePair::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t remote_msgs::LanePair::getCdrSerializedSize(
        const remote_msgs::LanePair& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void remote_msgs::LanePair::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_lane_id;
    scdr << m_is_reserve_lane;
    scdr << m_self_lane_id;
    scdr << m_left_lane_id;
    scdr << m_right_lane_id;

}

void remote_msgs::LanePair::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_lane_id;
    dcdr >> m_is_reserve_lane;
    dcdr >> m_self_lane_id;
    dcdr >> m_left_lane_id;
    dcdr >> m_right_lane_id;
}

/*!
 * @brief This function sets a value in member lane_id
 * @param _lane_id New value for member lane_id
 */
void remote_msgs::LanePair::lane_id(
        int32_t _lane_id)
{
    m_lane_id = _lane_id;
}

/*!
 * @brief This function returns the value of member lane_id
 * @return Value of member lane_id
 */
int32_t remote_msgs::LanePair::lane_id() const
{
    return m_lane_id;
}

/*!
 * @brief This function returns a reference to member lane_id
 * @return Reference to member lane_id
 */
int32_t& remote_msgs::LanePair::lane_id()
{
    return m_lane_id;
}

/*!
 * @brief This function sets a value in member is_reserve_lane
 * @param _is_reserve_lane New value for member is_reserve_lane
 */
void remote_msgs::LanePair::is_reserve_lane(
        bool _is_reserve_lane)
{
    m_is_reserve_lane = _is_reserve_lane;
}

/*!
 * @brief This function returns the value of member is_reserve_lane
 * @return Value of member is_reserve_lane
 */
bool remote_msgs::LanePair::is_reserve_lane() const
{
    return m_is_reserve_lane;
}

/*!
 * @brief This function returns a reference to member is_reserve_lane
 * @return Reference to member is_reserve_lane
 */
bool& remote_msgs::LanePair::is_reserve_lane()
{
    return m_is_reserve_lane;
}

/*!
 * @brief This function sets a value in member self_lane_id
 * @param _self_lane_id New value for member self_lane_id
 */
void remote_msgs::LanePair::self_lane_id(
        int32_t _self_lane_id)
{
    m_self_lane_id = _self_lane_id;
}

/*!
 * @brief This function returns the value of member self_lane_id
 * @return Value of member self_lane_id
 */
int32_t remote_msgs::LanePair::self_lane_id() const
{
    return m_self_lane_id;
}

/*!
 * @brief This function returns a reference to member self_lane_id
 * @return Reference to member self_lane_id
 */
int32_t& remote_msgs::LanePair::self_lane_id()
{
    return m_self_lane_id;
}

/*!
 * @brief This function sets a value in member left_lane_id
 * @param _left_lane_id New value for member left_lane_id
 */
void remote_msgs::LanePair::left_lane_id(
        int32_t _left_lane_id)
{
    m_left_lane_id = _left_lane_id;
}

/*!
 * @brief This function returns the value of member left_lane_id
 * @return Value of member left_lane_id
 */
int32_t remote_msgs::LanePair::left_lane_id() const
{
    return m_left_lane_id;
}

/*!
 * @brief This function returns a reference to member left_lane_id
 * @return Reference to member left_lane_id
 */
int32_t& remote_msgs::LanePair::left_lane_id()
{
    return m_left_lane_id;
}

/*!
 * @brief This function sets a value in member right_lane_id
 * @param _right_lane_id New value for member right_lane_id
 */
void remote_msgs::LanePair::right_lane_id(
        int32_t _right_lane_id)
{
    m_right_lane_id = _right_lane_id;
}

/*!
 * @brief This function returns the value of member right_lane_id
 * @return Value of member right_lane_id
 */
int32_t remote_msgs::LanePair::right_lane_id() const
{
    return m_right_lane_id;
}

/*!
 * @brief This function returns a reference to member right_lane_id
 * @return Reference to member right_lane_id
 */
int32_t& remote_msgs::LanePair::right_lane_id()
{
    return m_right_lane_id;
}


size_t remote_msgs::LanePair::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;








    return current_align;
}

bool remote_msgs::LanePair::isKeyDefined()
{
    return false;
}

void remote_msgs::LanePair::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}


remote_msgs::VehicleStatus::VehicleStatus()
{
    // m_position_longitude com.eprosima.idl.parser.typecode.PrimitiveTypeCode@62bd765
    m_position_longitude = 0.0;
    // m_position_latitude com.eprosima.idl.parser.typecode.PrimitiveTypeCode@dd3b207
    m_position_latitude = 0.0;
    // m_heading com.eprosima.idl.parser.typecode.PrimitiveTypeCode@551bdc27
    m_heading = 0.0;
    // m_position_altitude com.eprosima.idl.parser.typecode.PrimitiveTypeCode@58fdd99
    m_position_altitude = 0.0;
    // m_speed com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6b1274d2
    m_speed = 0.0;
    // m_yawrate com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7bc1a03d
    m_yawrate = 0.0;
    // m_gear_position com.eprosima.idl.parser.typecode.PrimitiveTypeCode@70b0b186
    m_gear_position = 0;
    // m_acceleration com.eprosima.idl.parser.typecode.PrimitiveTypeCode@ba8d91c
    m_acceleration = 0.0;
    // m_steering_angle com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7364985f
    m_steering_angle = 0.0;
    // m_wheel_angle com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5d20e46
    m_wheel_angle = 0.0;
    // m_ebrake_status com.eprosima.idl.parser.typecode.PrimitiveTypeCode@6a472554
    m_ebrake_status = 0;
    // m_indicator_left com.eprosima.idl.parser.typecode.PrimitiveTypeCode@61d47554
    m_indicator_left = false;
    // m_indicator_right com.eprosima.idl.parser.typecode.PrimitiveTypeCode@69b794e2
    m_indicator_right = false;
    // m_high_beam_status com.eprosima.idl.parser.typecode.PrimitiveTypeCode@3f200884
    m_high_beam_status = false;
    // m_low_beam_status com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4d339552
    m_low_beam_status = false;
    // m_emergency_light_status com.eprosima.idl.parser.typecode.PrimitiveTypeCode@f0f2775
    m_emergency_light_status = false;
    // m_timestamp com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5a4aa2f2
    m_timestamp = 0;
    // m_power_mode com.eprosima.idl.parser.typecode.EnumTypeCode@6591f517
    m_power_mode = remote_msgs::POWERMODE_OFF;
    // m_loc_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@345965f2
    m_loc_lane_id = 0;
    // m_cruise_lane_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@429bd883
    m_cruise_lane_id = 0;
    // m_local_lanes com.eprosima.idl.parser.typecode.AliasTypeCode@4d49af10

    // m_driving_efficiency com.eprosima.idl.parser.typecode.PrimitiveTypeCode@279ad2e3
    m_driving_efficiency = false;
    // m_control_mode com.eprosima.idl.parser.typecode.PrimitiveTypeCode@58134517
    m_control_mode = 0;
    // m_vehicle_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4450d156
    m_vehicle_id = 0;

}

remote_msgs::VehicleStatus::~VehicleStatus()
{
























}

remote_msgs::VehicleStatus::VehicleStatus(
        const VehicleStatus& x)
{
    m_position_longitude = x.m_position_longitude;
    m_position_latitude = x.m_position_latitude;
    m_heading = x.m_heading;
    m_position_altitude = x.m_position_altitude;
    m_speed = x.m_speed;
    m_yawrate = x.m_yawrate;
    m_gear_position = x.m_gear_position;
    m_acceleration = x.m_acceleration;
    m_steering_angle = x.m_steering_angle;
    m_wheel_angle = x.m_wheel_angle;
    m_ebrake_status = x.m_ebrake_status;
    m_indicator_left = x.m_indicator_left;
    m_indicator_right = x.m_indicator_right;
    m_high_beam_status = x.m_high_beam_status;
    m_low_beam_status = x.m_low_beam_status;
    m_emergency_light_status = x.m_emergency_light_status;
    m_timestamp = x.m_timestamp;
    m_power_mode = x.m_power_mode;
    m_loc_lane_id = x.m_loc_lane_id;
    m_cruise_lane_id = x.m_cruise_lane_id;
    m_local_lanes = x.m_local_lanes;
    m_driving_efficiency = x.m_driving_efficiency;
    m_control_mode = x.m_control_mode;
    m_vehicle_id = x.m_vehicle_id;
}

remote_msgs::VehicleStatus::VehicleStatus(
        VehicleStatus&& x)
{
    m_position_longitude = x.m_position_longitude;
    m_position_latitude = x.m_position_latitude;
    m_heading = x.m_heading;
    m_position_altitude = x.m_position_altitude;
    m_speed = x.m_speed;
    m_yawrate = x.m_yawrate;
    m_gear_position = x.m_gear_position;
    m_acceleration = x.m_acceleration;
    m_steering_angle = x.m_steering_angle;
    m_wheel_angle = x.m_wheel_angle;
    m_ebrake_status = x.m_ebrake_status;
    m_indicator_left = x.m_indicator_left;
    m_indicator_right = x.m_indicator_right;
    m_high_beam_status = x.m_high_beam_status;
    m_low_beam_status = x.m_low_beam_status;
    m_emergency_light_status = x.m_emergency_light_status;
    m_timestamp = x.m_timestamp;
    m_power_mode = x.m_power_mode;
    m_loc_lane_id = x.m_loc_lane_id;
    m_cruise_lane_id = x.m_cruise_lane_id;
    m_local_lanes = std::move(x.m_local_lanes);
    m_driving_efficiency = x.m_driving_efficiency;
    m_control_mode = x.m_control_mode;
    m_vehicle_id = x.m_vehicle_id;
}

remote_msgs::VehicleStatus& remote_msgs::VehicleStatus::operator =(
        const VehicleStatus& x)
{

    m_position_longitude = x.m_position_longitude;
    m_position_latitude = x.m_position_latitude;
    m_heading = x.m_heading;
    m_position_altitude = x.m_position_altitude;
    m_speed = x.m_speed;
    m_yawrate = x.m_yawrate;
    m_gear_position = x.m_gear_position;
    m_acceleration = x.m_acceleration;
    m_steering_angle = x.m_steering_angle;
    m_wheel_angle = x.m_wheel_angle;
    m_ebrake_status = x.m_ebrake_status;
    m_indicator_left = x.m_indicator_left;
    m_indicator_right = x.m_indicator_right;
    m_high_beam_status = x.m_high_beam_status;
    m_low_beam_status = x.m_low_beam_status;
    m_emergency_light_status = x.m_emergency_light_status;
    m_timestamp = x.m_timestamp;
    m_power_mode = x.m_power_mode;
    m_loc_lane_id = x.m_loc_lane_id;
    m_cruise_lane_id = x.m_cruise_lane_id;
    m_local_lanes = x.m_local_lanes;
    m_driving_efficiency = x.m_driving_efficiency;
    m_control_mode = x.m_control_mode;
    m_vehicle_id = x.m_vehicle_id;

    return *this;
}

remote_msgs::VehicleStatus& remote_msgs::VehicleStatus::operator =(
        VehicleStatus&& x)
{

    m_position_longitude = x.m_position_longitude;
    m_position_latitude = x.m_position_latitude;
    m_heading = x.m_heading;
    m_position_altitude = x.m_position_altitude;
    m_speed = x.m_speed;
    m_yawrate = x.m_yawrate;
    m_gear_position = x.m_gear_position;
    m_acceleration = x.m_acceleration;
    m_steering_angle = x.m_steering_angle;
    m_wheel_angle = x.m_wheel_angle;
    m_ebrake_status = x.m_ebrake_status;
    m_indicator_left = x.m_indicator_left;
    m_indicator_right = x.m_indicator_right;
    m_high_beam_status = x.m_high_beam_status;
    m_low_beam_status = x.m_low_beam_status;
    m_emergency_light_status = x.m_emergency_light_status;
    m_timestamp = x.m_timestamp;
    m_power_mode = x.m_power_mode;
    m_loc_lane_id = x.m_loc_lane_id;
    m_cruise_lane_id = x.m_cruise_lane_id;
    m_local_lanes = std::move(x.m_local_lanes);
    m_driving_efficiency = x.m_driving_efficiency;
    m_control_mode = x.m_control_mode;
    m_vehicle_id = x.m_vehicle_id;

    return *this;
}

bool remote_msgs::VehicleStatus::operator ==(
        const VehicleStatus& x) const
{

    return (m_position_longitude == x.m_position_longitude && m_position_latitude == x.m_position_latitude && m_heading == x.m_heading && m_position_altitude == x.m_position_altitude && m_speed == x.m_speed && m_yawrate == x.m_yawrate && m_gear_position == x.m_gear_position && m_acceleration == x.m_acceleration && m_steering_angle == x.m_steering_angle && m_wheel_angle == x.m_wheel_angle && m_ebrake_status == x.m_ebrake_status && m_indicator_left == x.m_indicator_left && m_indicator_right == x.m_indicator_right && m_high_beam_status == x.m_high_beam_status && m_low_beam_status == x.m_low_beam_status && m_emergency_light_status == x.m_emergency_light_status && m_timestamp == x.m_timestamp && m_power_mode == x.m_power_mode && m_loc_lane_id == x.m_loc_lane_id && m_cruise_lane_id == x.m_cruise_lane_id && m_local_lanes == x.m_local_lanes && m_driving_efficiency == x.m_driving_efficiency && m_control_mode == x.m_control_mode && m_vehicle_id == x.m_vehicle_id);
}

bool remote_msgs::VehicleStatus::operator !=(
        const VehicleStatus& x) const
{
    return !(*this == x);
}

size_t remote_msgs::VehicleStatus::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < 100; ++a)
    {
        current_alignment += remote_msgs::LanePair::getMaxCdrSerializedSize(current_alignment);}

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t remote_msgs::VehicleStatus::getCdrSerializedSize(
        const remote_msgs::VehicleStatus& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.local_lanes().size(); ++a)
    {
        current_alignment += remote_msgs::LanePair::getCdrSerializedSize(data.local_lanes().at(a), current_alignment);}

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void remote_msgs::VehicleStatus::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_position_longitude;
    scdr << m_position_latitude;
    scdr << m_heading;
    scdr << m_position_altitude;
    scdr << m_speed;
    scdr << m_yawrate;
    scdr << m_gear_position;
    scdr << m_acceleration;
    scdr << m_steering_angle;
    scdr << m_wheel_angle;
    scdr << m_ebrake_status;
    scdr << m_indicator_left;
    scdr << m_indicator_right;
    scdr << m_high_beam_status;
    scdr << m_low_beam_status;
    scdr << m_emergency_light_status;
    scdr << m_timestamp;
    scdr << (uint32_t)m_power_mode;
    scdr << m_loc_lane_id;
    scdr << m_cruise_lane_id;
    scdr << m_local_lanes;
    scdr << m_driving_efficiency;
    scdr << m_control_mode;
    scdr << m_vehicle_id;

}

void remote_msgs::VehicleStatus::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_position_longitude;
    dcdr >> m_position_latitude;
    dcdr >> m_heading;
    dcdr >> m_position_altitude;
    dcdr >> m_speed;
    dcdr >> m_yawrate;
    dcdr >> m_gear_position;
    dcdr >> m_acceleration;
    dcdr >> m_steering_angle;
    dcdr >> m_wheel_angle;
    dcdr >> m_ebrake_status;
    dcdr >> m_indicator_left;
    dcdr >> m_indicator_right;
    dcdr >> m_high_beam_status;
    dcdr >> m_low_beam_status;
    dcdr >> m_emergency_light_status;
    dcdr >> m_timestamp;
    {
        uint32_t enum_value = 0;
        dcdr >> enum_value;
        m_power_mode = (remote_msgs::PowerModeType)enum_value;
    }

    dcdr >> m_loc_lane_id;
    dcdr >> m_cruise_lane_id;
    dcdr >> m_local_lanes;
    dcdr >> m_driving_efficiency;
    dcdr >> m_control_mode;
    dcdr >> m_vehicle_id;
}

/*!
 * @brief This function sets a value in member position_longitude
 * @param _position_longitude New value for member position_longitude
 */
void remote_msgs::VehicleStatus::position_longitude(
        double _position_longitude)
{
    m_position_longitude = _position_longitude;
}

/*!
 * @brief This function returns the value of member position_longitude
 * @return Value of member position_longitude
 */
double remote_msgs::VehicleStatus::position_longitude() const
{
    return m_position_longitude;
}

/*!
 * @brief This function returns a reference to member position_longitude
 * @return Reference to member position_longitude
 */
double& remote_msgs::VehicleStatus::position_longitude()
{
    return m_position_longitude;
}

/*!
 * @brief This function sets a value in member position_latitude
 * @param _position_latitude New value for member position_latitude
 */
void remote_msgs::VehicleStatus::position_latitude(
        double _position_latitude)
{
    m_position_latitude = _position_latitude;
}

/*!
 * @brief This function returns the value of member position_latitude
 * @return Value of member position_latitude
 */
double remote_msgs::VehicleStatus::position_latitude() const
{
    return m_position_latitude;
}

/*!
 * @brief This function returns a reference to member position_latitude
 * @return Reference to member position_latitude
 */
double& remote_msgs::VehicleStatus::position_latitude()
{
    return m_position_latitude;
}

/*!
 * @brief This function sets a value in member heading
 * @param _heading New value for member heading
 */
void remote_msgs::VehicleStatus::heading(
        double _heading)
{
    m_heading = _heading;
}

/*!
 * @brief This function returns the value of member heading
 * @return Value of member heading
 */
double remote_msgs::VehicleStatus::heading() const
{
    return m_heading;
}

/*!
 * @brief This function returns a reference to member heading
 * @return Reference to member heading
 */
double& remote_msgs::VehicleStatus::heading()
{
    return m_heading;
}

/*!
 * @brief This function sets a value in member position_altitude
 * @param _position_altitude New value for member position_altitude
 */
void remote_msgs::VehicleStatus::position_altitude(
        float _position_altitude)
{
    m_position_altitude = _position_altitude;
}

/*!
 * @brief This function returns the value of member position_altitude
 * @return Value of member position_altitude
 */
float remote_msgs::VehicleStatus::position_altitude() const
{
    return m_position_altitude;
}

/*!
 * @brief This function returns a reference to member position_altitude
 * @return Reference to member position_altitude
 */
float& remote_msgs::VehicleStatus::position_altitude()
{
    return m_position_altitude;
}

/*!
 * @brief This function sets a value in member speed
 * @param _speed New value for member speed
 */
void remote_msgs::VehicleStatus::speed(
        float _speed)
{
    m_speed = _speed;
}

/*!
 * @brief This function returns the value of member speed
 * @return Value of member speed
 */
float remote_msgs::VehicleStatus::speed() const
{
    return m_speed;
}

/*!
 * @brief This function returns a reference to member speed
 * @return Reference to member speed
 */
float& remote_msgs::VehicleStatus::speed()
{
    return m_speed;
}

/*!
 * @brief This function sets a value in member yawrate
 * @param _yawrate New value for member yawrate
 */
void remote_msgs::VehicleStatus::yawrate(
        float _yawrate)
{
    m_yawrate = _yawrate;
}

/*!
 * @brief This function returns the value of member yawrate
 * @return Value of member yawrate
 */
float remote_msgs::VehicleStatus::yawrate() const
{
    return m_yawrate;
}

/*!
 * @brief This function returns a reference to member yawrate
 * @return Reference to member yawrate
 */
float& remote_msgs::VehicleStatus::yawrate()
{
    return m_yawrate;
}

/*!
 * @brief This function sets a value in member gear_position
 * @param _gear_position New value for member gear_position
 */
void remote_msgs::VehicleStatus::gear_position(
        int32_t _gear_position)
{
    m_gear_position = _gear_position;
}

/*!
 * @brief This function returns the value of member gear_position
 * @return Value of member gear_position
 */
int32_t remote_msgs::VehicleStatus::gear_position() const
{
    return m_gear_position;
}

/*!
 * @brief This function returns a reference to member gear_position
 * @return Reference to member gear_position
 */
int32_t& remote_msgs::VehicleStatus::gear_position()
{
    return m_gear_position;
}

/*!
 * @brief This function sets a value in member acceleration
 * @param _acceleration New value for member acceleration
 */
void remote_msgs::VehicleStatus::acceleration(
        float _acceleration)
{
    m_acceleration = _acceleration;
}

/*!
 * @brief This function returns the value of member acceleration
 * @return Value of member acceleration
 */
float remote_msgs::VehicleStatus::acceleration() const
{
    return m_acceleration;
}

/*!
 * @brief This function returns a reference to member acceleration
 * @return Reference to member acceleration
 */
float& remote_msgs::VehicleStatus::acceleration()
{
    return m_acceleration;
}

/*!
 * @brief This function sets a value in member steering_angle
 * @param _steering_angle New value for member steering_angle
 */
void remote_msgs::VehicleStatus::steering_angle(
        float _steering_angle)
{
    m_steering_angle = _steering_angle;
}

/*!
 * @brief This function returns the value of member steering_angle
 * @return Value of member steering_angle
 */
float remote_msgs::VehicleStatus::steering_angle() const
{
    return m_steering_angle;
}

/*!
 * @brief This function returns a reference to member steering_angle
 * @return Reference to member steering_angle
 */
float& remote_msgs::VehicleStatus::steering_angle()
{
    return m_steering_angle;
}

/*!
 * @brief This function sets a value in member wheel_angle
 * @param _wheel_angle New value for member wheel_angle
 */
void remote_msgs::VehicleStatus::wheel_angle(
        float _wheel_angle)
{
    m_wheel_angle = _wheel_angle;
}

/*!
 * @brief This function returns the value of member wheel_angle
 * @return Value of member wheel_angle
 */
float remote_msgs::VehicleStatus::wheel_angle() const
{
    return m_wheel_angle;
}

/*!
 * @brief This function returns a reference to member wheel_angle
 * @return Reference to member wheel_angle
 */
float& remote_msgs::VehicleStatus::wheel_angle()
{
    return m_wheel_angle;
}

/*!
 * @brief This function sets a value in member ebrake_status
 * @param _ebrake_status New value for member ebrake_status
 */
void remote_msgs::VehicleStatus::ebrake_status(
        int32_t _ebrake_status)
{
    m_ebrake_status = _ebrake_status;
}

/*!
 * @brief This function returns the value of member ebrake_status
 * @return Value of member ebrake_status
 */
int32_t remote_msgs::VehicleStatus::ebrake_status() const
{
    return m_ebrake_status;
}

/*!
 * @brief This function returns a reference to member ebrake_status
 * @return Reference to member ebrake_status
 */
int32_t& remote_msgs::VehicleStatus::ebrake_status()
{
    return m_ebrake_status;
}

/*!
 * @brief This function sets a value in member indicator_left
 * @param _indicator_left New value for member indicator_left
 */
void remote_msgs::VehicleStatus::indicator_left(
        bool _indicator_left)
{
    m_indicator_left = _indicator_left;
}

/*!
 * @brief This function returns the value of member indicator_left
 * @return Value of member indicator_left
 */
bool remote_msgs::VehicleStatus::indicator_left() const
{
    return m_indicator_left;
}

/*!
 * @brief This function returns a reference to member indicator_left
 * @return Reference to member indicator_left
 */
bool& remote_msgs::VehicleStatus::indicator_left()
{
    return m_indicator_left;
}

/*!
 * @brief This function sets a value in member indicator_right
 * @param _indicator_right New value for member indicator_right
 */
void remote_msgs::VehicleStatus::indicator_right(
        bool _indicator_right)
{
    m_indicator_right = _indicator_right;
}

/*!
 * @brief This function returns the value of member indicator_right
 * @return Value of member indicator_right
 */
bool remote_msgs::VehicleStatus::indicator_right() const
{
    return m_indicator_right;
}

/*!
 * @brief This function returns a reference to member indicator_right
 * @return Reference to member indicator_right
 */
bool& remote_msgs::VehicleStatus::indicator_right()
{
    return m_indicator_right;
}

/*!
 * @brief This function sets a value in member high_beam_status
 * @param _high_beam_status New value for member high_beam_status
 */
void remote_msgs::VehicleStatus::high_beam_status(
        bool _high_beam_status)
{
    m_high_beam_status = _high_beam_status;
}

/*!
 * @brief This function returns the value of member high_beam_status
 * @return Value of member high_beam_status
 */
bool remote_msgs::VehicleStatus::high_beam_status() const
{
    return m_high_beam_status;
}

/*!
 * @brief This function returns a reference to member high_beam_status
 * @return Reference to member high_beam_status
 */
bool& remote_msgs::VehicleStatus::high_beam_status()
{
    return m_high_beam_status;
}

/*!
 * @brief This function sets a value in member low_beam_status
 * @param _low_beam_status New value for member low_beam_status
 */
void remote_msgs::VehicleStatus::low_beam_status(
        bool _low_beam_status)
{
    m_low_beam_status = _low_beam_status;
}

/*!
 * @brief This function returns the value of member low_beam_status
 * @return Value of member low_beam_status
 */
bool remote_msgs::VehicleStatus::low_beam_status() const
{
    return m_low_beam_status;
}

/*!
 * @brief This function returns a reference to member low_beam_status
 * @return Reference to member low_beam_status
 */
bool& remote_msgs::VehicleStatus::low_beam_status()
{
    return m_low_beam_status;
}

/*!
 * @brief This function sets a value in member emergency_light_status
 * @param _emergency_light_status New value for member emergency_light_status
 */
void remote_msgs::VehicleStatus::emergency_light_status(
        bool _emergency_light_status)
{
    m_emergency_light_status = _emergency_light_status;
}

/*!
 * @brief This function returns the value of member emergency_light_status
 * @return Value of member emergency_light_status
 */
bool remote_msgs::VehicleStatus::emergency_light_status() const
{
    return m_emergency_light_status;
}

/*!
 * @brief This function returns a reference to member emergency_light_status
 * @return Reference to member emergency_light_status
 */
bool& remote_msgs::VehicleStatus::emergency_light_status()
{
    return m_emergency_light_status;
}

/*!
 * @brief This function sets a value in member timestamp
 * @param _timestamp New value for member timestamp
 */
void remote_msgs::VehicleStatus::timestamp(
        uint64_t _timestamp)
{
    m_timestamp = _timestamp;
}

/*!
 * @brief This function returns the value of member timestamp
 * @return Value of member timestamp
 */
uint64_t remote_msgs::VehicleStatus::timestamp() const
{
    return m_timestamp;
}

/*!
 * @brief This function returns a reference to member timestamp
 * @return Reference to member timestamp
 */
uint64_t& remote_msgs::VehicleStatus::timestamp()
{
    return m_timestamp;
}

/*!
 * @brief This function sets a value in member power_mode
 * @param _power_mode New value for member power_mode
 */
void remote_msgs::VehicleStatus::power_mode(
        remote_msgs::PowerModeType _power_mode)
{
    m_power_mode = _power_mode;
}

/*!
 * @brief This function returns the value of member power_mode
 * @return Value of member power_mode
 */
remote_msgs::PowerModeType remote_msgs::VehicleStatus::power_mode() const
{
    return m_power_mode;
}

/*!
 * @brief This function returns a reference to member power_mode
 * @return Reference to member power_mode
 */
remote_msgs::PowerModeType& remote_msgs::VehicleStatus::power_mode()
{
    return m_power_mode;
}

/*!
 * @brief This function sets a value in member loc_lane_id
 * @param _loc_lane_id New value for member loc_lane_id
 */
void remote_msgs::VehicleStatus::loc_lane_id(
        int32_t _loc_lane_id)
{
    m_loc_lane_id = _loc_lane_id;
}

/*!
 * @brief This function returns the value of member loc_lane_id
 * @return Value of member loc_lane_id
 */
int32_t remote_msgs::VehicleStatus::loc_lane_id() const
{
    return m_loc_lane_id;
}

/*!
 * @brief This function returns a reference to member loc_lane_id
 * @return Reference to member loc_lane_id
 */
int32_t& remote_msgs::VehicleStatus::loc_lane_id()
{
    return m_loc_lane_id;
}

/*!
 * @brief This function sets a value in member cruise_lane_id
 * @param _cruise_lane_id New value for member cruise_lane_id
 */
void remote_msgs::VehicleStatus::cruise_lane_id(
        int32_t _cruise_lane_id)
{
    m_cruise_lane_id = _cruise_lane_id;
}

/*!
 * @brief This function returns the value of member cruise_lane_id
 * @return Value of member cruise_lane_id
 */
int32_t remote_msgs::VehicleStatus::cruise_lane_id() const
{
    return m_cruise_lane_id;
}

/*!
 * @brief This function returns a reference to member cruise_lane_id
 * @return Reference to member cruise_lane_id
 */
int32_t& remote_msgs::VehicleStatus::cruise_lane_id()
{
    return m_cruise_lane_id;
}

/*!
 * @brief This function copies the value in member local_lanes
 * @param _local_lanes New value to be copied in member local_lanes
 */
void remote_msgs::VehicleStatus::local_lanes(
        const remote_msgs::LaneArray& _local_lanes)
{
    m_local_lanes = _local_lanes;
}

/*!
 * @brief This function moves the value in member local_lanes
 * @param _local_lanes New value to be moved in member local_lanes
 */
void remote_msgs::VehicleStatus::local_lanes(
        remote_msgs::LaneArray&& _local_lanes)
{
    m_local_lanes = std::move(_local_lanes);
}

/*!
 * @brief This function returns a constant reference to member local_lanes
 * @return Constant reference to member local_lanes
 */
const remote_msgs::LaneArray& remote_msgs::VehicleStatus::local_lanes() const
{
    return m_local_lanes;
}

/*!
 * @brief This function returns a reference to member local_lanes
 * @return Reference to member local_lanes
 */
remote_msgs::LaneArray& remote_msgs::VehicleStatus::local_lanes()
{
    return m_local_lanes;
}
/*!
 * @brief This function sets a value in member driving_efficiency
 * @param _driving_efficiency New value for member driving_efficiency
 */
void remote_msgs::VehicleStatus::driving_efficiency(
        bool _driving_efficiency)
{
    m_driving_efficiency = _driving_efficiency;
}

/*!
 * @brief This function returns the value of member driving_efficiency
 * @return Value of member driving_efficiency
 */
bool remote_msgs::VehicleStatus::driving_efficiency() const
{
    return m_driving_efficiency;
}

/*!
 * @brief This function returns a reference to member driving_efficiency
 * @return Reference to member driving_efficiency
 */
bool& remote_msgs::VehicleStatus::driving_efficiency()
{
    return m_driving_efficiency;
}

/*!
 * @brief This function sets a value in member control_mode
 * @param _control_mode New value for member control_mode
 */
void remote_msgs::VehicleStatus::control_mode(
        int32_t _control_mode)
{
    m_control_mode = _control_mode;
}

/*!
 * @brief This function returns the value of member control_mode
 * @return Value of member control_mode
 */
int32_t remote_msgs::VehicleStatus::control_mode() const
{
    return m_control_mode;
}

/*!
 * @brief This function returns a reference to member control_mode
 * @return Reference to member control_mode
 */
int32_t& remote_msgs::VehicleStatus::control_mode()
{
    return m_control_mode;
}

/*!
 * @brief This function sets a value in member vehicle_id
 * @param _vehicle_id New value for member vehicle_id
 */
void remote_msgs::VehicleStatus::vehicle_id(
        uint32_t _vehicle_id)
{
    m_vehicle_id = _vehicle_id;
}

/*!
 * @brief This function returns the value of member vehicle_id
 * @return Value of member vehicle_id
 */
uint32_t remote_msgs::VehicleStatus::vehicle_id() const
{
    return m_vehicle_id;
}

/*!
 * @brief This function returns a reference to member vehicle_id
 * @return Reference to member vehicle_id
 */
uint32_t& remote_msgs::VehicleStatus::vehicle_id()
{
    return m_vehicle_id;
}


size_t remote_msgs::VehicleStatus::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



























    return current_align;
}

bool remote_msgs::VehicleStatus::isKeyDefined()
{
    return false;
}

void remote_msgs::VehicleStatus::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
                            
}

