// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RemoteControl.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__REMOTE_MSGS_REMOTECONTROL_HPP
#define FAST_DDS_GENERATED__REMOTE_MSGS_REMOTECONTROL_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(REMOTECONTROL_SOURCE)
#define REMOTECONTROL_DllAPI __declspec( dllexport )
#else
#define REMOTECONTROL_DllAPI __declspec( dllimport )
#endif // REMOTECONTROL_SOURCE
#else
#define REMOTECONTROL_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define REMOTECONTROL_DllAPI
#endif // _WIN32

namespace remote_msgs {

/*!
 * @brief This class represents the structure ControlCmd defined by the user in the IDL file.
 * @ingroup RemoteControl
 */
class ControlCmd
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ControlCmd()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ControlCmd()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ControlCmd that will be copied.
     */
    eProsima_user_DllExport ControlCmd(
            const ControlCmd& x)
    {
                    m_steering_angle_enable = x.m_steering_angle_enable;

                    m_steering_angle = x.m_steering_angle;

                    m_target_acceleration_enable = x.m_target_acceleration_enable;

                    m_target_acceleration = x.m_target_acceleration;

                    m_indicator_left_enable = x.m_indicator_left_enable;

                    m_indicator_left = x.m_indicator_left;

                    m_indicator_right_enable = x.m_indicator_right_enable;

                    m_indicator_right = x.m_indicator_right;

                    m_gear_position_enable = x.m_gear_position_enable;

                    m_gear_position = x.m_gear_position;

                    m_ebrake_status_enable = x.m_ebrake_status_enable;

                    m_ebrake_status = x.m_ebrake_status;

                    m_timestamp = x.m_timestamp;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ControlCmd that will be copied.
     */
    eProsima_user_DllExport ControlCmd(
            ControlCmd&& x) noexcept
    {
        m_steering_angle_enable = x.m_steering_angle_enable;
        m_steering_angle = x.m_steering_angle;
        m_target_acceleration_enable = x.m_target_acceleration_enable;
        m_target_acceleration = x.m_target_acceleration;
        m_indicator_left_enable = x.m_indicator_left_enable;
        m_indicator_left = x.m_indicator_left;
        m_indicator_right_enable = x.m_indicator_right_enable;
        m_indicator_right = x.m_indicator_right;
        m_gear_position_enable = x.m_gear_position_enable;
        m_gear_position = x.m_gear_position;
        m_ebrake_status_enable = x.m_ebrake_status_enable;
        m_ebrake_status = x.m_ebrake_status;
        m_timestamp = x.m_timestamp;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ControlCmd that will be copied.
     */
    eProsima_user_DllExport ControlCmd& operator =(
            const ControlCmd& x)
    {

                    m_steering_angle_enable = x.m_steering_angle_enable;

                    m_steering_angle = x.m_steering_angle;

                    m_target_acceleration_enable = x.m_target_acceleration_enable;

                    m_target_acceleration = x.m_target_acceleration;

                    m_indicator_left_enable = x.m_indicator_left_enable;

                    m_indicator_left = x.m_indicator_left;

                    m_indicator_right_enable = x.m_indicator_right_enable;

                    m_indicator_right = x.m_indicator_right;

                    m_gear_position_enable = x.m_gear_position_enable;

                    m_gear_position = x.m_gear_position;

                    m_ebrake_status_enable = x.m_ebrake_status_enable;

                    m_ebrake_status = x.m_ebrake_status;

                    m_timestamp = x.m_timestamp;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ControlCmd that will be copied.
     */
    eProsima_user_DllExport ControlCmd& operator =(
            ControlCmd&& x) noexcept
    {

        m_steering_angle_enable = x.m_steering_angle_enable;
        m_steering_angle = x.m_steering_angle;
        m_target_acceleration_enable = x.m_target_acceleration_enable;
        m_target_acceleration = x.m_target_acceleration;
        m_indicator_left_enable = x.m_indicator_left_enable;
        m_indicator_left = x.m_indicator_left;
        m_indicator_right_enable = x.m_indicator_right_enable;
        m_indicator_right = x.m_indicator_right;
        m_gear_position_enable = x.m_gear_position_enable;
        m_gear_position = x.m_gear_position;
        m_ebrake_status_enable = x.m_ebrake_status_enable;
        m_ebrake_status = x.m_ebrake_status;
        m_timestamp = x.m_timestamp;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ControlCmd object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ControlCmd& x) const
    {
        return (m_steering_angle_enable == x.m_steering_angle_enable &&
           m_steering_angle == x.m_steering_angle &&
           m_target_acceleration_enable == x.m_target_acceleration_enable &&
           m_target_acceleration == x.m_target_acceleration &&
           m_indicator_left_enable == x.m_indicator_left_enable &&
           m_indicator_left == x.m_indicator_left &&
           m_indicator_right_enable == x.m_indicator_right_enable &&
           m_indicator_right == x.m_indicator_right &&
           m_gear_position_enable == x.m_gear_position_enable &&
           m_gear_position == x.m_gear_position &&
           m_ebrake_status_enable == x.m_ebrake_status_enable &&
           m_ebrake_status == x.m_ebrake_status &&
           m_timestamp == x.m_timestamp);
    }

    /*!
     * @brief Comparison operator.
     * @param x ControlCmd object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ControlCmd& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member steering_angle_enable
     * @param _steering_angle_enable New value for member steering_angle_enable
     */
    eProsima_user_DllExport void steering_angle_enable(
            bool _steering_angle_enable)
    {
        m_steering_angle_enable = _steering_angle_enable;
    }

    /*!
     * @brief This function returns the value of member steering_angle_enable
     * @return Value of member steering_angle_enable
     */
    eProsima_user_DllExport bool steering_angle_enable() const
    {
        return m_steering_angle_enable;
    }

    /*!
     * @brief This function returns a reference to member steering_angle_enable
     * @return Reference to member steering_angle_enable
     */
    eProsima_user_DllExport bool& steering_angle_enable()
    {
        return m_steering_angle_enable;
    }


    /*!
     * @brief This function sets a value in member steering_angle
     * @param _steering_angle New value for member steering_angle
     */
    eProsima_user_DllExport void steering_angle(
            float _steering_angle)
    {
        m_steering_angle = _steering_angle;
    }

    /*!
     * @brief This function returns the value of member steering_angle
     * @return Value of member steering_angle
     */
    eProsima_user_DllExport float steering_angle() const
    {
        return m_steering_angle;
    }

    /*!
     * @brief This function returns a reference to member steering_angle
     * @return Reference to member steering_angle
     */
    eProsima_user_DllExport float& steering_angle()
    {
        return m_steering_angle;
    }


    /*!
     * @brief This function sets a value in member target_acceleration_enable
     * @param _target_acceleration_enable New value for member target_acceleration_enable
     */
    eProsima_user_DllExport void target_acceleration_enable(
            bool _target_acceleration_enable)
    {
        m_target_acceleration_enable = _target_acceleration_enable;
    }

    /*!
     * @brief This function returns the value of member target_acceleration_enable
     * @return Value of member target_acceleration_enable
     */
    eProsima_user_DllExport bool target_acceleration_enable() const
    {
        return m_target_acceleration_enable;
    }

    /*!
     * @brief This function returns a reference to member target_acceleration_enable
     * @return Reference to member target_acceleration_enable
     */
    eProsima_user_DllExport bool& target_acceleration_enable()
    {
        return m_target_acceleration_enable;
    }


    /*!
     * @brief This function sets a value in member target_acceleration
     * @param _target_acceleration New value for member target_acceleration
     */
    eProsima_user_DllExport void target_acceleration(
            float _target_acceleration)
    {
        m_target_acceleration = _target_acceleration;
    }

    /*!
     * @brief This function returns the value of member target_acceleration
     * @return Value of member target_acceleration
     */
    eProsima_user_DllExport float target_acceleration() const
    {
        return m_target_acceleration;
    }

    /*!
     * @brief This function returns a reference to member target_acceleration
     * @return Reference to member target_acceleration
     */
    eProsima_user_DllExport float& target_acceleration()
    {
        return m_target_acceleration;
    }


    /*!
     * @brief This function sets a value in member indicator_left_enable
     * @param _indicator_left_enable New value for member indicator_left_enable
     */
    eProsima_user_DllExport void indicator_left_enable(
            bool _indicator_left_enable)
    {
        m_indicator_left_enable = _indicator_left_enable;
    }

    /*!
     * @brief This function returns the value of member indicator_left_enable
     * @return Value of member indicator_left_enable
     */
    eProsima_user_DllExport bool indicator_left_enable() const
    {
        return m_indicator_left_enable;
    }

    /*!
     * @brief This function returns a reference to member indicator_left_enable
     * @return Reference to member indicator_left_enable
     */
    eProsima_user_DllExport bool& indicator_left_enable()
    {
        return m_indicator_left_enable;
    }


    /*!
     * @brief This function sets a value in member indicator_left
     * @param _indicator_left New value for member indicator_left
     */
    eProsima_user_DllExport void indicator_left(
            bool _indicator_left)
    {
        m_indicator_left = _indicator_left;
    }

    /*!
     * @brief This function returns the value of member indicator_left
     * @return Value of member indicator_left
     */
    eProsima_user_DllExport bool indicator_left() const
    {
        return m_indicator_left;
    }

    /*!
     * @brief This function returns a reference to member indicator_left
     * @return Reference to member indicator_left
     */
    eProsima_user_DllExport bool& indicator_left()
    {
        return m_indicator_left;
    }


    /*!
     * @brief This function sets a value in member indicator_right_enable
     * @param _indicator_right_enable New value for member indicator_right_enable
     */
    eProsima_user_DllExport void indicator_right_enable(
            bool _indicator_right_enable)
    {
        m_indicator_right_enable = _indicator_right_enable;
    }

    /*!
     * @brief This function returns the value of member indicator_right_enable
     * @return Value of member indicator_right_enable
     */
    eProsima_user_DllExport bool indicator_right_enable() const
    {
        return m_indicator_right_enable;
    }

    /*!
     * @brief This function returns a reference to member indicator_right_enable
     * @return Reference to member indicator_right_enable
     */
    eProsima_user_DllExport bool& indicator_right_enable()
    {
        return m_indicator_right_enable;
    }


    /*!
     * @brief This function sets a value in member indicator_right
     * @param _indicator_right New value for member indicator_right
     */
    eProsima_user_DllExport void indicator_right(
            bool _indicator_right)
    {
        m_indicator_right = _indicator_right;
    }

    /*!
     * @brief This function returns the value of member indicator_right
     * @return Value of member indicator_right
     */
    eProsima_user_DllExport bool indicator_right() const
    {
        return m_indicator_right;
    }

    /*!
     * @brief This function returns a reference to member indicator_right
     * @return Reference to member indicator_right
     */
    eProsima_user_DllExport bool& indicator_right()
    {
        return m_indicator_right;
    }


    /*!
     * @brief This function sets a value in member gear_position_enable
     * @param _gear_position_enable New value for member gear_position_enable
     */
    eProsima_user_DllExport void gear_position_enable(
            bool _gear_position_enable)
    {
        m_gear_position_enable = _gear_position_enable;
    }

    /*!
     * @brief This function returns the value of member gear_position_enable
     * @return Value of member gear_position_enable
     */
    eProsima_user_DllExport bool gear_position_enable() const
    {
        return m_gear_position_enable;
    }

    /*!
     * @brief This function returns a reference to member gear_position_enable
     * @return Reference to member gear_position_enable
     */
    eProsima_user_DllExport bool& gear_position_enable()
    {
        return m_gear_position_enable;
    }


    /*!
     * @brief This function sets a value in member gear_position
     * @param _gear_position New value for member gear_position
     */
    eProsima_user_DllExport void gear_position(
            int32_t _gear_position)
    {
        m_gear_position = _gear_position;
    }

    /*!
     * @brief This function returns the value of member gear_position
     * @return Value of member gear_position
     */
    eProsima_user_DllExport int32_t gear_position() const
    {
        return m_gear_position;
    }

    /*!
     * @brief This function returns a reference to member gear_position
     * @return Reference to member gear_position
     */
    eProsima_user_DllExport int32_t& gear_position()
    {
        return m_gear_position;
    }


    /*!
     * @brief This function sets a value in member ebrake_status_enable
     * @param _ebrake_status_enable New value for member ebrake_status_enable
     */
    eProsima_user_DllExport void ebrake_status_enable(
            bool _ebrake_status_enable)
    {
        m_ebrake_status_enable = _ebrake_status_enable;
    }

    /*!
     * @brief This function returns the value of member ebrake_status_enable
     * @return Value of member ebrake_status_enable
     */
    eProsima_user_DllExport bool ebrake_status_enable() const
    {
        return m_ebrake_status_enable;
    }

    /*!
     * @brief This function returns a reference to member ebrake_status_enable
     * @return Reference to member ebrake_status_enable
     */
    eProsima_user_DllExport bool& ebrake_status_enable()
    {
        return m_ebrake_status_enable;
    }


    /*!
     * @brief This function sets a value in member ebrake_status
     * @param _ebrake_status New value for member ebrake_status
     */
    eProsima_user_DllExport void ebrake_status(
            int32_t _ebrake_status)
    {
        m_ebrake_status = _ebrake_status;
    }

    /*!
     * @brief This function returns the value of member ebrake_status
     * @return Value of member ebrake_status
     */
    eProsima_user_DllExport int32_t ebrake_status() const
    {
        return m_ebrake_status;
    }

    /*!
     * @brief This function returns a reference to member ebrake_status
     * @return Reference to member ebrake_status
     */
    eProsima_user_DllExport int32_t& ebrake_status()
    {
        return m_ebrake_status;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }



private:

    bool m_steering_angle_enable{false};
    float m_steering_angle{0.0};
    bool m_target_acceleration_enable{false};
    float m_target_acceleration{0.0};
    bool m_indicator_left_enable{false};
    bool m_indicator_left{false};
    bool m_indicator_right_enable{false};
    bool m_indicator_right{false};
    bool m_gear_position_enable{false};
    int32_t m_gear_position{0};
    bool m_ebrake_status_enable{false};
    int32_t m_ebrake_status{0};
    uint64_t m_timestamp{0};

};

} // namespace remote_msgs

#endif // _FAST_DDS_GENERATED_REMOTE_MSGS_REMOTECONTROL_HPP_


